log:
  path: logs # 请使用实际的地址进行替换
env:
  name: prod


spring:
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    #cache: false # true # 开启缓存
    cache: false
#chatgpt:
#  key: